name: Deploy Quiz-Online App

on:
  push:
    branches:
      - main  # триггер срабатывает на пуш в main ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Check for test files
        id: check_tests
        run: |
          if ! ls **/*.spec.ts **/*.test.ts 1> /dev/null 2>&1; then
            echo "No tests found, skipping test step"
            echo "::set-output name=tests_found::false"
          else
            echo "::set-output name=tests_found::true"
          fi

      - name: Run tests
        if: steps.check_tests.outputs.tests_found == 'true'
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Deploy to production
        run: |
          # Команды для деплоя
